import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>


      <header>
        <nav>
          <img src="" alt="" />
          <a href="/"> Home</a>
          <a href="/events"> Events</a>
          <a href="/about"> About Us</a>
        </nav>
      </header>
      <main className={styles.main}>

      </main>

      {/* <Footer className={styles.footer}>

      </Footer> */}
    </div>
  )
}
