import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({title}) {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>


      <header>
        <nav>
          <img src="" alt="" />
          <a href="/"> Home</a>
          <a href="/events"> Events</a>
          <a href="/about"> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href=''>
          <img/>
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nemo quisquam molestiae odit nam praesentium nesciunt nulla, deserunt voluptatum commodi aspernatur omnis ipsum consequuntur fugit quo numquam, assumenda quam pariatur.</p>
        </a>
        <a href=''>
          <img/>
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nemo quisquam molestiae odit nam praesentium nesciunt nulla, deserunt voluptatum commodi aspernatur omnis ipsum consequuntur fugit quo numquam, assumenda quam pariatur.</p>
        </a>
        <a href=''>
          <img/>
          <h2>Events in Spain</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nemo quisquam molestiae odit nam praesentium nesciunt nulla, deserunt voluptatum commodi aspernatur omnis ipsum consequuntur fugit quo numquam, assumenda quam pariatur.</p>
        </a>

      </main>

      <footer className={styles.footer}>
        <p> © 2023 Time to Code - A project </p>
      </footer>
    </div>
  )
}


export function getServerSideProps(){
  
  return{
    props:{
      title: "Hello everyone",

    }
  }

}
