import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { HomePage } from '@/src/components/home/HomePage'
import { Header } from '@/src/components/header/Header'
import { Footer } from '@/src/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Events App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>

      <Header />
      <HomePage data={data} />
      <Footer />
    </div>
  )
}


export async function getServerSideProps(){
  const { events_categories } = await import('/data/data.json')
  return{
    props:{
      data: events_categories,
    }
  }
}
